GET http://127.0.0.1:8080/flowers

###
POST http://127.0.0.1:8080/flowers
Content-Type: application/json

{
  "id" : 3,
  "sepalLength": 15.5,
  "color": "blue",
  "price": 100,
  "flowerType": "Rose"
}